---
language: python
services: docker

env:
  global:
    - ROLE_NAME: wikijs
  matrix:
    - MOLECULE_DISTRIB: debian10:latest

before_install:
  - curl https://gist.githubusercontent.com/supertarto/e9b6a648f07c4e2776cb00a10aa4a697/raw/d58d5104e71d808c64ad38214ae084628eda2f67/travis-ci-molecule.sh | sudo bash


install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-$ROLE_NAME supertarto.$ROLE_NAME
  - cd supertarto.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
